### ISSUE TITLE
Can't run  classify_digits.py

### ISSUE THREAD

**Issue by mazixes** [globality-corp/sklearn-hierarchical-classification#19]
Hi all,

I can't seem to be able to run the example. After installation with pip I got:
`ImportError: No module named 'sklearn_hierarchical_classification.tests'`

When I cloned the repo and manually copied tests to my venv, I got:
```
Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        37
           3       1.00      1.00      1.00        41
           7       1.00      1.00      1.00        30
           8       0.97      1.00      0.99        36
           9       1.00      0.97      0.99        36

    accuracy                           0.99       180
   macro avg       0.99      0.99      0.99       180
weighted avg       0.99      0.99      0.99       180

Traceback (most recent call last):
  File "../sklearn-hierarchical-classification/examples/classify_digits.py", line 87, in <module>
    classify_digits()
  File "../sklearn-hierarchical-classification/examples/classify_digits.py", line 81, in classify_digits
    graph_,
  File "/r/tcal/work/maziar/work/zothers/cesar/aidarc/env/lib/python3.5/site-packages/sklearn_hierarchical_classification/metrics.py", line 234, in h_fbeta_score
    hP = h_precision_score(y_true, y_pred, class_hierarchy)
  File "/r/tcal/work/maziar/work/zothers/cesar/aidarc/env/lib/python3.5/site-packages/sklearn_hierarchical_classification/metrics.py", line 141, in h_precision_score
    y_true_ = fill_ancestors(y_true, graph=class_hierarchy)
  File "/r/tcal/work/maziar/work/zothers/cesar/aidarc/env/lib/python3.5/site-packages/sklearn_hierarchical_classification/metrics.py", line 102, in fill_ancestors
    y_[tuple(np.meshgrid(ix_rows, ancestors))] = 1
IndexError: arrays used as indices must be of integer (or boolean) type

```

**Comment by fbenites** [comment]
Hi

two things, 
- how you copied? which env, etc.
- try cloning, then pip install -e . 

The second thing is basically here:
https://colab.research.google.com/drive/1JR9Y92LWOcsNf5z9oRns9vF90hzSNDkq#scrollTo=hTCuqtgbqIAf&forceEdit=true&offline=true&sandboxMode=true

In the colab env it will not work at first, you need to restart. 
Resuming:
- create env
- activate env
- git clone ...
- pip install -e .

Hope this helps!

**Comment by mazixes** [comment]
Thanks @fbenites. 

> how you copied? which env, etc.

I cloned the repo and then copied the "tests" folder of repo into my created virtual environment. This got rid of the first error.

For the second error, I was not using colab or jupyter environment. After reading your reply, I commented out the last part of example code and it worked.

Thanks again.

**Comment by adamhadani** [comment]
Marking as resolved per last comment! thanks @fbenites
