### ISSUE TITLE
Support string input

### ISSUE THREAD

**Issue by hacktuarial** [globality-corp/sklearn-hierarchical-classification#24]
I want to fit a HierarchicalClassifier where the base model is a pipeline composed of a [TfidfVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) followed by some classifier. However, the data representation in this package seems strongly tied to sparse matrices, which evidently do not support string types (see script below). Is it possible to relax the assumption of csr_matrix to enable this use case?

```
from scipy import sparse
import numpy as np

if __name__ == '__main__':
    X = np.array(["the quick", "brown fox", "jumped", "over the lazy dog"]).reshape(-1, 1)
    sparse.csr_matrix(X)
```

throws 
```
Traceback (most recent call last):
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/base.py", line 326, in asformat
    return convert_method(copy=copy)
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/coo.py", line 406, in tocsr
    data = np.empty_like(self.data, dtype=upcast(self.dtype))
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/sputils.py", line 52, in upcast
    raise TypeError('no supported conversion for types: %r' % (args,))
TypeError: no supported conversion for types: (dtype('<U17'),)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sparse_string.py", line 6, in <module>
    sparse.csr_matrix(X)
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 88, in __init__
    self._set_self(self.__class__(coo_matrix(arg1, dtype=dtype)))
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 37, in __init__
    arg1 = arg1.asformat(self.format)
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/base.py", line 328, in asformat
    return convert_method()
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/coo.py", line 406, in tocsr
    data = np.empty_like(self.data, dtype=upcast(self.dtype))
  File "/Users/tsweetser/.pyenv/versions/jupyter/lib/python3.6/site-packages/scipy/sparse/sputils.py", line 52, in upcast
    raise TypeError('no supported conversion for types: %r' % (args,))
TypeError: no supported conversion for types: (dtype('<U17'),)
```

**Comment by adamhadani** [comment]
I suspect may also be solved as side-effect of merging in #20 which gives more control to user over the feature preprocessing pipeline. @fbenites any chance we'll get a unit-test/example in there anytime soon? if not I'll try my hand at making enough sense of it to clean up / add tests and merge..

**Comment by hacktuarial** [comment]
Would it be helpful for me to write a unit test for my use case?

**Comment by fbenites** [comment]
@adamhadani check the following commit:
https://github.com/globality-corp/sklearn-hierarchical-classification/pull/20/commits/666a8fae5143ad8403203c8b2ecf0d7cf8555176
It is an "integration test" using a multi-label version of 20 news groups, and own preprocessing (could be used as an example also).

**Comment by adamhadani** [comment]
Tracking via PR #33  going forward - will update once merged

**Comment by selik** [comment]
PR #33 Looks like it's merged to the `develop` branch, but when I install that branch, I still get `ValueError: could not convert string to float`.

**Comment by fbenites** [comment]
where do you get that exaclty? Maybe you need to activate the feature_extraction="raw".

**Comment by selik** [comment]
@fbenites It doesn't appear to have that parameter. Maybe that indicates my installation from the source didn't override the one from PyPI.

**Comment by krrishdholakia** [comment]
still facing this issue. any updates ?

**Comment by krrishdholakia** [comment]
using the bert transformer from huggingface as a vectorizer, but unable to do so. 
`base_estimator = Pipeline(
    [
        ("vectorizer", bert_transformer),
        ("classifier", classifier),
    ]
)`
