### ISSUE TITLE
"IndexError: index 1 is out of bounds for axis 0 with size 1" when predicting - bug?

### ISSUE THREAD

**Issue by Make42** [globality-corp/sklearn-hierarchical-classification#44]
I get the error

Traceback (most recent call last):
  [...]
  File "[...]\sklearn_hierarchical_classification\classifier.py", line 324, in predict_proba
    y_pred = apply_along_rows(_classify, X=X)
  File "[...]\sklearn_hierarchical_classification\array.py", line 20, in apply_along_rows
    return np.array([
  File "[...]\sklearn_hierarchical_classification\array.py", line 21, in <listcomp>
    func(X.getrow(i))
  File "[...]\sklearn_hierarchical_classification\classifier.py", line 313, in _classify
    _, scores = self._recursive_predict(x, root=self.root)
  File "[...]\sklearn_hierarchical_classification\classifier.py", line 592, in _recursive_predict
    score = probs[argmax]
IndexError: index 1 is out of bounds for axis 0 with size 1

here the lines are 

                   probs = clf.decision_function(x)
                    argmax = np.argmax(probs)
                    score = probs[argmax]

Could it be that it should be

                   probs = clf.decision_function(x)
                    argmax = probs.argmax(axis=1)
                    score = probs[range(range(x.shape[0]), argmax]

where the third line is the acutally important change? Possibly one could also write for this particular case the same code that you used for "raw", namely 

                    probs = clf.decision_function([x])
                    argmax = np.argmax(probs)
                    score = probs[0, argmax]

I don't see why the code is different for "raw" and "preprocessed".

**Comment by Make42** [comment]
I think I found the bug: For Classifiers like LinearSVC, the methods like [`decision_function`](https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html#sklearn.svm.LinearSVC.decision_function) returns only **one** value, if there are only two classes. Thus the [code](https://github.com/globality-corp/sklearn-hierarchical-classification/blob/1de19f782d992a82dace895f9c24a0fc074baeeb/sklearn_hierarchical_classification/classifier.py#L583)

            if self.use_decision_function and hasattr(clf, "decision_function"):
                if self.feature_extraction == "raw":
                    probs = clf.decision_function([x])
                    argmax = np.argmax(probs)
                    score = probs[0, argmax]

                else:
                    probs = clf.decision_function(x)
                    argmax = np.argmax(probs)
                    score = probs[argmax]

should actually be

            if self.use_decision_function and hasattr(clf, "decision_function"):
                probs = clf.decision_function([x]) if self.feature_extraction == "raw" else clf.decision_function(x)
                last_axis = probs.ndim-1
                if probs.ndim == 1 and probs.shape[0] == 1:
                    probs = np.concatenate((-probs, probs), axis=last_axis)
                argmax = probs.argmax(axis=last_axis)
                score = probs[argmax] if last_axis == 0 else probs[0, argmax]
